import { Profile, Skill, Education, Experience, ResearchPaper, BlogPost, PortfolioProject, Testimonial } from './firestore';

const mockProfile: Profile = {
  name: "Dr. Logeshwaran J",
  title: "Researcher",
  subtitle: "Assistant Professor — Christ University, Bangalore",
  bio: "Jaganathan Logeshwaran is an accomplished researcher and academic with expertise in Networking and Communication Systems. He specializes in 5G Communication Networks and Computational Intelligence Systems. He has published over 100 research papers and is cited more than 5350 times on Google Scholar. He has also published over 300 utility patents, five design patents, and five books. Recognized as a World Top 2% Scientist by Stanford University with Elsevier in both 2024 and 2025.",
  email: "logeshwaran.j@christuniversity.in",
  phone: "+91 80 4012 9100",
  address: "Department of Computer Science, Christ University, Bangalore Campus, India",
  socialLinks: {
    linkedin: "https://www.linkedin.com/in/logeshwaran-j/",
    twitter: "#",
    instagram: "#",
    facebook: "#",
  },
  bannerImage: "/assets/images/banner/real-banner.jpg",
  profileImage: "/assets/images/logo/real-profile.jpg",
  yearsOfExperience: 10,
  projectsCompleted: 100,
  happyClients: 5350,
  clientReviews: 300,
};

const mockSkills: Skill[] = [
  { name: "5G/6G Communication Networks", category: "development", percentage: 95, icon: "fa-light fa-tower-broadcast", projectCount: 40 },
  { name: "IoT Systems", category: "development", percentage: 90, icon: "fa-light fa-microchip", projectCount: 35 },
  { name: "Deep Learning", category: "development", percentage: 90, icon: "fa-light fa-brain", projectCount: 30 },
  { name: "Research & Publications", category: "design", percentage: 100, icon: "fa-light fa-book", projectCount: 100 },
  { name: "Wireless Networks", category: "design", percentage: 95, icon: "fa-light fa-wifi", projectCount: 50 },
  { name: "Edge & Fog Computing", category: "development", percentage: 85, icon: "fa-light fa-cloud", projectCount: 20 },
  { name: "Patent Development", category: "design", percentage: 100, icon: "fa-light fa-lightbulb", projectCount: 300 },
  { name: "Academic Mentoring", category: "design", percentage: 90, icon: "fa-light fa-chalkboard-teacher", projectCount: 25 },
];

const mockEducation: Education[] = [
  {
    title: "Ph.D. in Information & Communication Systems",
    institution: "Sri Eshwar College of Engineering",
    period: "Completed",
    description: "Research focused on Wireless Networks and Communication Systems under the guidance of Dr. N. Shanmugasundaram.",
  },
  {
    title: "M.E. in Communication Systems",
    institution: "Mahendra Engineering College, Tamil Nadu",
    period: "Completed",
    description: "Specialized in communication systems engineering, building deep expertise in wireless and network technologies.",
  },
  {
    title: "B.E. in Electronics & Communication Engineering",
    institution: "Mahendra Engineering College, Tamil Nadu",
    period: "Completed",
    description: "Strong foundation in electronics, communication engineering, embedded systems, and signal processing.",
  },
  {
    title: "World Top 2% Scientist Recognition",
    institution: "Stanford University with Elsevier",
    period: "2024 & 2025",
    description: "Recognized among the World Top 2% Scientists globally, securing 16,606th rank in 2025 by Stanford University with Elsevier.",
  },
];

const mockExperience: Experience[] = [
  {
    company: "Christ University, Bangalore",
    duration: "Current",
    role: "Assistant Professor",
    description: "Teaching and research in computer science, specializing in 5G/6G communication networks, IoT, and computational intelligence. Mentoring students in cutting-edge research.",
  },
  {
    company: "Mahendra College of Engineering, Salem",
    duration: "Since 2015",
    role: "Assistant Professor",
    description: "Began academic career in 2015, teaching and conducting research in networking and communication systems. Published extensively in top-tier journals.",
  },
  {
    company: "Academic Journals & Conferences",
    duration: "2024 - 2025",
    role: "Reviewer & Guest Editor",
    description: "Served as Reviewer, Session Chair, and Guest Editor for multiple top-tier international journals and conferences.",
  },
  {
    company: "International Conferences (ICCCNT, ICICV, ICPCSN, ICREC)",
    duration: "2024 - 2025",
    role: "Conference Chair & Presenter",
    description: "Presented research and chaired sessions at 16th ICCCNT 2025, 6th ICICV 2025, 4th IC Networks & Cryptology, ICPCSN 2025, ICAICCIT 2024, and 2nd WCONF.",
  },
];

const mockResearchPapers: ResearchPaper[] = [
  {
    id: "1",
    title: "Toward Smart 5G and 6G: Standardization of AI-Native Network Architectures and Semantic Communication Protocols",
    authors: ["Logeshwaran J", "Kurunandan Jain", "Prabhakar Krishnan", "Prabu Pachiyannan", "Muhammad Attique Khan", "Yang Li"],
    journal: "IEEE Communications Standards Magazine",
    year: 2025,
    abstract: "This paper explores the standardization of AI-native network architectures and semantic communication protocols for the evolution toward smart 5G and 6G networks, proposing novel frameworks for next-generation wireless systems.",
    is_private: false,
    slug: "smart-5g-6g-ai-native-architectures",
  },
  {
    id: "2",
    title: "Optimizing Resource Management Using Hybrid Metaheuristic Algorithm for Fog Layer Design in Edge Computing",
    authors: ["Logeshwaran J", "Sanjaikanth E V S Pillai", "Santhosh Paramasivam", "Kiran Polimetla", "Selvaraj Dhanasekaran", "Krishna Kant Agrawal", "Satya Prakash Yadav", "Gianluca Gatto"],
    journal: "Systems and Soft Computing",
    year: 2025,
    abstract: "Proposes a hybrid metaheuristic algorithm to optimize resource management in fog computing layers, improving efficiency and reducing latency in edge computing deployments for IoT applications.",
    is_private: false,
    slug: "hybrid-metaheuristic-fog-edge-computing",
  },
  {
    id: "3",
    title: "An Enhanced Performance Analysis of Load Based Resource Sharing Framework for MIMO Systems in 5G Communication Systems",
    authors: ["Logeshwaran J", "Shobhit K. Patel", "Om Prakash Kumar", "Fahad Ahmed Al-Zahrani"],
    journal: "Scientific Reports (Nature)",
    year: 2025,
    abstract: "Presents an enhanced load-based resource sharing framework for MIMO systems in 5G networks, demonstrating significant performance improvements in throughput and spectral efficiency.",
    is_private: false,
    slug: "load-resource-sharing-mimo-5g",
  },
  {
    id: "4",
    title: "An Improved LSTM Based Thermal Prediction and Control Algorithm for Battery Management System in Hybrid Electric Vehicles",
    authors: ["Logeshwaran J", "Prabu P", "Ganeshkumar P", "Prabhakar Krishnan", "Dhanasekaran S", "Weiwei Jiang"],
    journal: "International Communications in Heat and Mass Transfer",
    year: 2025,
    abstract: "Introduces an improved LSTM-based thermal prediction and control algorithm for battery management systems in hybrid electric vehicles, enhancing safety and battery longevity.",
    is_private: false,
    slug: "lstm-thermal-prediction-battery-hev",
  },
  {
    id: "5",
    title: "Design and Optimization of a MXene-Based Terahertz Surface Plasmon Resonance Sensor for Malaria Detection",
    authors: ["Logeshwaran J", "Haitham Alsaif", "Jacob Wekalao", "Naim Ben Ali", "Omar Kahouli", "Shobhit K. Patel", "Ammar Armghan"],
    journal: "Plasmonics (Springer)",
    year: 2024,
    abstract: "Designs and optimizes a MXene-based terahertz surface plasmon resonance sensor for rapid and accurate malaria detection, demonstrating high sensitivity and specificity.",
    is_private: false,
    slug: "mxene-thz-spr-malaria-detection",
  },
  {
    id: "6",
    title: "Hybrid Optimization for Efficient 6G IoT Traffic Management and Multi-Routing Strategy",
    authors: ["Logeshwaran J", "Shobhit K. Patel", "Om Prakash Kumar", "Fahad Ahmed Al-Zahrani"],
    journal: "Scientific Reports (Nature)",
    year: 2024,
    abstract: "Proposes a hybrid optimization approach for efficient IoT traffic management in 6G networks with a multi-routing strategy that significantly reduces latency and improves reliability.",
    is_private: false,
    slug: "hybrid-optimization-6g-iot-traffic",
  },
  {
    id: "7",
    title: "Improving Crop Production Using an Agro-Deep Learning Framework in Precision Agriculture",
    authors: ["Logeshwaran J", "Durgesh Srivastava", "K. Sree Kumar", "M. Jenolin Rex", "Amal Al-Rasheed", "Masresha Getahun", "Ben Othman Soufiene"],
    journal: "BMC Bioinformatics",
    year: 2024,
    abstract: "Develops an agro-deep learning framework for precision agriculture that improves crop production by leveraging advanced neural networks for crop health monitoring and yield prediction.",
    is_private: false,
    slug: "agro-deep-learning-precision-agriculture",
  },
  {
    id: "8",
    title: "Enhancing Mobility Management in 5G Networks Using Deep Residual LSTM Model",
    authors: ["Logeshwaran J", "Abdullah Baz", "Yuvaraj Natarajan", "Shobhit K. Patel"],
    journal: "Applied Soft Computing (Elsevier)",
    year: 2024,
    abstract: "Enhances mobility management in 5G networks through a deep residual LSTM model that predicts user mobility patterns for seamless handovers and improved quality of service.",
    is_private: false,
    slug: "mobility-management-5g-deep-lstm",
  },
  {
    id: "9",
    title: "The Feasibility Analysis of Load Based Resource Optimization Algorithm for Cooperative Communication in 5G Wireless Ad-Hoc Networks",
    authors: ["Logeshwaran J", "R. Kannadasan", "P.M. Benson Mansingh", "A. Mutharasan", "N. Yuvaraj", "S. Venkatasubramanian", "Mohammed H. Alsharif", "Peerapong Uthansakul", "Monthippa Uthansakul"],
    journal: "Alexandria Engineering Journal",
    year: 2024,
    abstract: "Analyzes the feasibility of a load-based resource optimization algorithm for cooperative communication in 5G wireless ad-hoc networks, showing improved resource utilization and network throughput.",
    is_private: true,
    slug: "load-resource-optimization-5g-adhoc",
  },
  {
    id: "10",
    title: "Quantum Cryptography for Secure Communication in IoT Networks",
    authors: ["Logeshwaran J", "Sandhiya B"],
    journal: "Research Project — Internal",
    year: 2025,
    abstract: "An ongoing research project investigating quantum cryptography techniques for establishing secure and tamper-proof communication channels in IoT networks.",
    is_private: true,
    slug: "quantum-cryptography-iot-networks",
  },
];

const mockBlogPosts: BlogPost[] = [
  {
    id: "1",
    title: "The Evolution from 5G to 6G: What to Expect in Next-Gen Communication",
    slug: "evolution-5g-to-6g",
    excerpt: "Exploring the roadmap from current 5G deployments to the future 6G vision, covering AI-native architectures and semantic communication.",
    content: "<p>The transition from 5G to 6G represents more than just an incremental upgrade — it's a fundamental paradigm shift in how we conceive wireless communication systems.</p><p>With AI-native network architectures at the core, 6G promises to deliver unprecedented capabilities including terabit-per-second speeds, sub-millisecond latency, and intelligent network orchestration.</p><p>In this article, we explore the key technologies driving this evolution, including semantic communication protocols, digital twins, and reconfigurable intelligent surfaces (RIS).</p>",
    author: "Dr. Logeshwaran J",
    date: "October 24, 2025",
    thumbnail: "/assets/images/blog/blog-img-1.jpg",
    tags: ["5G", "6G", "AI", "Communication"],
  },
  {
    id: "2",
    title: "IoT in Precision Agriculture: How Deep Learning is Transforming Farming",
    slug: "iot-precision-agriculture-deep-learning",
    excerpt: "How IoT sensors combined with deep learning frameworks are revolutionizing crop monitoring, yield prediction, and sustainable farming.",
    content: "<p>The convergence of Internet of Things (IoT) and deep learning is creating transformative opportunities in precision agriculture.</p><p>By deploying smart sensors across farmlands and analyzing the data through advanced neural networks, farmers can now make data-driven decisions about irrigation, fertilization, and pest control.</p><p>Our research on the agro-deep learning framework demonstrates how these technologies can significantly improve crop yields while reducing resource consumption.</p>",
    author: "Dr. Logeshwaran J",
    date: "October 15, 2024",
    thumbnail: "/assets/images/blog/blog-img-2.jpg",
    tags: ["IoT", "Agriculture", "Deep Learning"],
  },
  {
    id: "3",
    title: "Edge Computing and Fog Layers: Optimizing Resource Management for IoT",
    slug: "edge-computing-fog-layers-optimization",
    excerpt: "Understanding the role of fog computing in edge computing architectures and how hybrid metaheuristic algorithms optimize resource allocation.",
    content: "<p>As IoT devices proliferate, the need for efficient edge computing architectures becomes increasingly critical.</p><p>Fog computing provides an intermediate layer between cloud data centers and IoT endpoints, enabling faster processing and reduced bandwidth consumption.</p><p>In this article, we discuss our recent work on hybrid metaheuristic algorithms for fog layer design that achieve significant improvements in resource utilization and response times.</p>",
    author: "Dr. Logeshwaran J",
    date: "June 11, 2025",
    thumbnail: "/assets/images/blog/blog-img-3.jpg",
    tags: ["Edge Computing", "Fog Computing", "IoT"],
  },
];

const mockProjects: PortfolioProject[] = [
  {
    id: "1",
    title: "IoT Healthcare Monitoring & Alert System",
    category: "IoT & Healthcare",
    image: "/assets/images/latest-portfolio/portfoli-img-1.jpg",
    description: "A patented IoT-integrated healthcare monitoring and alert system for real-time patient health tracking.",
    link: "#",
  },
  {
    id: "2",
    title: "AI-Based 5G Low Latency Transmission",
    category: "5G Communication",
    image: "/assets/images/latest-portfolio/portfoli-img-2.jpg",
    description: "An improved AI-based low latency data transmission system for 5G communication networks.",
    link: "#",
  },
  {
    id: "3",
    title: "Solar Powered Air Pollution Monitoring",
    category: "IoT & Environment",
    image: "/assets/images/latest-portfolio/portfoli-img-3.jpg",
    description: "A patented solar-powered air pollution monitoring system using IoT sensors for real-time environmental data.",
    link: "#",
  },
  {
    id: "4",
    title: "Quantum Cryptography for IoT Security",
    category: "Quantum Computing",
    image: "/assets/images/latest-portfolio/portfoli-img-4.jpg",
    description: "Research project on quantum cryptography techniques for secure communication in IoT networks.",
    link: "#",
  },
  {
    id: "5",
    title: "Device to Analyse Cement Quality",
    category: "IoT & Industrial",
    image: "/assets/images/latest-portfolio/portfoli-img-1.jpg",
    description: "A patented hardware device utilizing localized sensors to analyze the quality metrics of cement.",
    link: "#",
  },
  {
    id: "6",
    title: "Smart Logistics Tracking and Monitoring Device",
    category: "IoT & Supply Chain",
    image: "/assets/images/latest-portfolio/portfoli-img-2.jpg",
    description: "A patented smart logistics tracking and remote monitoring device utilizing GPS and cellular IoT connectivity.",
    link: "#",
  },
  {
    id: "7",
    title: "IoT Weather Station Airship",
    category: "IoT & Environment",
    image: "/assets/images/latest-portfolio/portfoli-img-3.jpg",
    description: "A patented aerial IoT weather station airship capable of comprehensive atmospheric data collection.",
    link: "#",
  },
  {
    id: "8",
    title: "Device For Measuring Ph Value of Fluid",
    category: "Hardware Sensor",
    image: "/assets/images/latest-portfolio/portfoli-img-4.jpg",
    description: "A patented hardware sensor designed for highly accurate real-time measurement of fluid pH values.",
    link: "#",
  },
  {
    id: "9",
    title: "Noise Pollution and Light Pollution Control System",
    category: "Smart City",
    image: "/assets/images/latest-portfolio/portfoli-img-1.jpg",
    description: "A patented smart city architecture system for monitoring and mitigating urban noise and light pollution.",
    link: "#",
  },
  {
    id: "10",
    title: "AI Based Brain Cancer Detection Device",
    category: "AI & Healthcare",
    image: "/assets/images/latest-portfolio/portfoli-img-2.jpg",
    description: "A patented diagnostic tool leveraging neural networks for early-stage brain cancer detection.",
    link: "#",
  },
];

const mockTestimonials: Testimonial[] = [
  {
    id: "1",
    name: "Dr. Shobhit K. Patel",
    role: "Research Collaborator",
    quote: "Working with Dr. Logeshwaran has been an incredible experience. His depth of knowledge in 5G and wireless communication systems is truly inspiring. Our collaborative papers have made significant contributions to the field.",
    image: "/assets/images/testimonial/bg-image-1png.png",
  },
  {
    id: "2",
    name: "Dr. Prabhakar Krishnan",
    role: "Co-Author & Colleague",
    quote: "Dr. Logeshwaran's contributions to our joint research on AI-native network architectures have been invaluable. A brilliant researcher with excellent collaborative skills and deep technical expertise.",
    image: "/assets/images/testimonial/bg-image-2.png",
  },
  {
    id: "3",
    name: "Research Student",
    role: "PhD Scholar, Christ University",
    quote: "As a mentor, Dr. Logeshwaran has guided me through my research journey with patience, wisdom, and unwavering support. His expertise in communication systems is unmatched.",
    image: "/assets/images/testimonial/bg-image-1png.png",
  },
];
export { mockProfile, mockSkills, mockEducation, mockExperience, mockResearchPapers, mockBlogPosts, mockProjects, mockTestimonials };
